name: Deploy Frontend to recipe.dev.ibessonniy.ru (Dev)

on:
  push:
    branches:
      - dev
    paths:
      - 'projects/frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive' # Важно для работы с подмодулями

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Используйте актуальную версию Node.js для вашего Angular проекта

      - name: Navigate to frontend submodule
        run: cd projects/frontend

      - name: Install dependencies
        run: npm install

      - name: Build Angular application
        run: npm run build -- --configuration=production # Используйте вашу команду сборки

      - name: Deploy to Server
        run: |
          rsync -e "ssh -p 22 -o StrictHostKeyChecking=no" --archive --compress --delete \
            projects/frontend/dist/recipe-angular/ strizhki@recipe.dev.ibessonniy.ru:/var/www/recipe.dev.ibessonniy.ru/
